//Get Posts
export const GET_POSTS= 'GET_POSTS';
export const GET_POSTS_SUCCESS='GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR='GET_POSTS_ERROR';
//Get Comments
export const GET_COMMENTS= 'GET_COMMENTS';
export const GET_COMMENTS_SUCCESS='GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR='GET_COMMENTS_ERROR';
//Add Comments  
export const ADD_COMMENT='ADD_COMMENT';
export const ADD_COMMENT_SUCCESS='ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR='ADD_COMMENT_ERROR';
export const GET_DATA_STATE = 'GET_DATA_STATE';
export const GET_DATA_STATE_SUCCESS = 'GET_DATA_STATE_SUCCESS';

